package com.teamvanar.aboutme

import android.content.Context
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import android.view.inputmethod.InputMethodManager
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import androidx.databinding.DataBindingUtil
import com.teamvanar.aboutme.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {

    /**
     * ActivityMainBinding is generated by compiler based on layout file's name. Camel case followed
     * by 'Binding' is used to name the class.
     */
    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)

        // Compiler generates names of views in the layout, converting them to Camel case.
        // View with 'done_button' as ID is 'doneButton' in the binding object.
        binding.doneButton.setOnClickListener {
            addNickname()
        }

        binding.nicknameText.setOnClickListener {
            updateNickname()
        }
    }

    private fun addNickname() {
        binding.nicknameText.text = binding.nicknameEdit.text.toString()

        binding.nicknameText.visibility = View.VISIBLE
        binding.nicknameEdit.visibility = View.GONE
        binding.doneButton.visibility = View.GONE
    }

    private fun updateNickname() {
        // Shortcut to set multiple fields. '.binding' is not needed for fields inside 'apply {}'
        binding.apply {
            nicknameEdit.visibility = View.VISIBLE
            nicknameEdit.requestFocus()

            doneButton.visibility = View.VISIBLE
            nicknameText.visibility = View.GONE
        }

        // Show the keyboard.
        val imm = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
        imm.showSoftInput(binding.nicknameEdit, 0)
    }
}